package io.sentrius.sso.core.model.sessions;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

/**
 * Entity to store SSH/Terminal session summaries generated by AI analysis.
 * Summaries are created by analyzing terminal command logs and session metadata.
 */
@Entity
@Table(name = "ssh_session_summaries")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class SshSessionSummary {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @Column(name = "session_id", nullable = false, unique = true)
    private Long sessionId;
    
    @Column(name = "user_identifier", nullable = false)
    private String userIdentifier;
    
    @Column(name = "target_identifier")
    private String targetIdentifier;
    
    @Column(name = "session_start")
    private Instant sessionStart;
    
    @Column(name = "session_end")
    private Instant sessionEnd;
    
    @Column(name = "summary", columnDefinition = "TEXT")
    private String summary;
    
    @Column(name = "commands_executed", columnDefinition = "TEXT")
    private String commandsExecuted;
    
    @Column(name = "key_activities", columnDefinition = "TEXT")
    private String keyActivities;
    
    @Column(name = "risk_indicators", columnDefinition = "TEXT")
    private String riskIndicators;
    
    @Column(name = "terminal_log_count")
    private Integer terminalLogCount;
    
    @Column(name = "created_at", nullable = false)
    private Instant createdAt;
    
    @Column(name = "updated_at")
    private Instant updatedAt;
    
    @PrePersist
    protected void onCreate() {
        if (createdAt == null) {
            createdAt = Instant.now();
        }
        updatedAt = Instant.now();
    }
    
    @PreUpdate
    protected void onUpdate() {
        updatedAt = Instant.now();
    }
}
