{{- if .Values.debug.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: debug
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: debug
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  containers:
    - name: debug
      image: curlimages/curl:latest
      command: ["sleep"]
      args: ["3600"]
{{- end }}
