apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sentrius
  labels:
    {{- include "sentrius.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sentrius
  template:
    metadata:
      labels:
        app: sentrius
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-postgres.{{ .Release.Namespace }}.svc.cluster.local 5432; do echo waiting for postgres; sleep 2; done;' ]
        - name: wait-for-keycloak
          image: busybox
          command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-keycloak.{{ .Release.Namespace }}.svc.cluster.local
           30081; do echo waiting for postgres; sleep 2; done;' ]
      containers:
        - name: sentrius
          image: "{{ .Values.sentrius.image.repository }}:{{ .Values.sentrius.image.tag }}"
          imagePullPolicy: {{ .Values.sentrius.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.sentrius.port }}
          volumeMounts:
            - name: config-volume
              mountPath: /config
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rds-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rds-secret
                  key: password
            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rds-secret
                  key: keystore-password
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-config
