apiVersion: v1
kind: Service
metadata:
  name: sentrius-ssh
spec:
  selector:
    app: sentrius-ssh # Remove release label from selector
  ports:
    - protocol: TCP
      port: {{ .Values.ssh.port }}
      targetPort: {{ .Values.ssh.port }}
  type: ClusterIP
