// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/session.proto

package io.dataguardians.protobuf;

public final class Session {
  private Session() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code io.dataguardians.protobuf.TriggerAction}
   */
  public enum TriggerAction
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NO_ACTION = 0;</code>
     */
    NO_ACTION(0),
    /**
     * <code>LOG_ACTION = 1;</code>
     */
    LOG_ACTION(1),
    /**
     * <code>ALERT_ACTION = 2;</code>
     */
    ALERT_ACTION(2),
    /**
     * <code>WARN_ACTION = 3;</code>
     */
    WARN_ACTION(3),
    /**
     * <code>DENY_ACTION = 4;</code>
     */
    DENY_ACTION(4),
    /**
     * <code>JIT_ACTION = 5;</code>
     */
    JIT_ACTION(5),
    /**
     * <code>RECORD_ACTION = 6;</code>
     */
    RECORD_ACTION(6),
    /**
     * <code>APPROVE_ACTION = 7;</code>
     */
    APPROVE_ACTION(7),
    /**
     * <code>PERSISTENT_MESSAGE = 8;</code>
     */
    PERSISTENT_MESSAGE(8),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NO_ACTION = 0;</code>
     */
    public static final int NO_ACTION_VALUE = 0;
    /**
     * <code>LOG_ACTION = 1;</code>
     */
    public static final int LOG_ACTION_VALUE = 1;
    /**
     * <code>ALERT_ACTION = 2;</code>
     */
    public static final int ALERT_ACTION_VALUE = 2;
    /**
     * <code>WARN_ACTION = 3;</code>
     */
    public static final int WARN_ACTION_VALUE = 3;
    /**
     * <code>DENY_ACTION = 4;</code>
     */
    public static final int DENY_ACTION_VALUE = 4;
    /**
     * <code>JIT_ACTION = 5;</code>
     */
    public static final int JIT_ACTION_VALUE = 5;
    /**
     * <code>RECORD_ACTION = 6;</code>
     */
    public static final int RECORD_ACTION_VALUE = 6;
    /**
     * <code>APPROVE_ACTION = 7;</code>
     */
    public static final int APPROVE_ACTION_VALUE = 7;
    /**
     * <code>PERSISTENT_MESSAGE = 8;</code>
     */
    public static final int PERSISTENT_MESSAGE_VALUE = 8;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TriggerAction valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static TriggerAction forNumber(int value) {
      switch (value) {
        case 0: return NO_ACTION;
        case 1: return LOG_ACTION;
        case 2: return ALERT_ACTION;
        case 3: return WARN_ACTION;
        case 4: return DENY_ACTION;
        case 5: return JIT_ACTION;
        case 6: return RECORD_ACTION;
        case 7: return APPROVE_ACTION;
        case 8: return PERSISTENT_MESSAGE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TriggerAction>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TriggerAction> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TriggerAction>() {
            public TriggerAction findValueByNumber(int number) {
              return TriggerAction.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.dataguardians.protobuf.Session.getDescriptor().getEnumTypes().get(0);
    }

    private static final TriggerAction[] VALUES = values();

    public static TriggerAction valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TriggerAction(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:io.dataguardians.protobuf.TriggerAction)
  }

  /**
   * Protobuf enum {@code io.dataguardians.protobuf.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>HEARTBEAT = 0;</code>
     */
    HEARTBEAT(0),
    /**
     * <code>USER_DATA = 1;</code>
     */
    USER_DATA(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>HEARTBEAT = 0;</code>
     */
    public static final int HEARTBEAT_VALUE = 0;
    /**
     * <code>USER_DATA = 1;</code>
     */
    public static final int USER_DATA_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return HEARTBEAT;
        case 1: return USER_DATA;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.dataguardians.protobuf.Session.getDescriptor().getEnumTypes().get(1);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:io.dataguardians.protobuf.MessageType)
  }

  public interface TriggerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.dataguardians.protobuf.Trigger)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.io.dataguardians.protobuf.TriggerAction action = 1;</code>
     * @return The enum numeric value on the wire for action.
     */
    int getActionValue();
    /**
     * <code>.io.dataguardians.protobuf.TriggerAction action = 1;</code>
     * @return The action.
     */
    io.dataguardians.protobuf.Session.TriggerAction getAction();

    /**
     * <code>string description = 2;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 2;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * Protobuf type {@code io.dataguardians.protobuf.Trigger}
   */
  public static final class Trigger extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.dataguardians.protobuf.Trigger)
      TriggerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Trigger.newBuilder() to construct.
    private Trigger(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Trigger() {
      action_ = 0;
      description_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Trigger();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Trigger(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              action_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.dataguardians.protobuf.Session.internal_static_io_dataguardians_protobuf_Trigger_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.dataguardians.protobuf.Session.internal_static_io_dataguardians_protobuf_Trigger_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.dataguardians.protobuf.Session.Trigger.class, io.dataguardians.protobuf.Session.Trigger.Builder.class);
    }

    public static final int ACTION_FIELD_NUMBER = 1;
    private int action_;
    /**
     * <code>.io.dataguardians.protobuf.TriggerAction action = 1;</code>
     * @return The enum numeric value on the wire for action.
     */
    @java.lang.Override public int getActionValue() {
      return action_;
    }
    /**
     * <code>.io.dataguardians.protobuf.TriggerAction action = 1;</code>
     * @return The action.
     */
    @java.lang.Override public io.dataguardians.protobuf.Session.TriggerAction getAction() {
      @SuppressWarnings("deprecation")
      io.dataguardians.protobuf.Session.TriggerAction result = io.dataguardians.protobuf.Session.TriggerAction.valueOf(action_);
      return result == null ? io.dataguardians.protobuf.Session.TriggerAction.UNRECOGNIZED : result;
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 2;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 2;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (action_ != io.dataguardians.protobuf.Session.TriggerAction.NO_ACTION.getNumber()) {
        output.writeEnum(1, action_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, description_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (action_ != io.dataguardians.protobuf.Session.TriggerAction.NO_ACTION.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, action_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, description_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.dataguardians.protobuf.Session.Trigger)) {
        return super.equals(obj);
      }
      io.dataguardians.protobuf.Session.Trigger other = (io.dataguardians.protobuf.Session.Trigger) obj;

      if (action_ != other.action_) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + action_;
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.dataguardians.protobuf.Session.Trigger parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.dataguardians.protobuf.Session.Trigger parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.dataguardians.protobuf.Session.Trigger parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.dataguardians.protobuf.Session.Trigger parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.dataguardians.protobuf.Session.Trigger parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.dataguardians.protobuf.Session.Trigger parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.dataguardians.protobuf.Session.Trigger parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.dataguardians.protobuf.Session.Trigger parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.dataguardians.protobuf.Session.Trigger parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.dataguardians.protobuf.Session.Trigger parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.dataguardians.protobuf.Session.Trigger parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.dataguardians.protobuf.Session.Trigger parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.dataguardians.protobuf.Session.Trigger prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.dataguardians.protobuf.Trigger}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.dataguardians.protobuf.Trigger)
        io.dataguardians.protobuf.Session.TriggerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.dataguardians.protobuf.Session.internal_static_io_dataguardians_protobuf_Trigger_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.dataguardians.protobuf.Session.internal_static_io_dataguardians_protobuf_Trigger_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.dataguardians.protobuf.Session.Trigger.class, io.dataguardians.protobuf.Session.Trigger.Builder.class);
      }

      // Construct using io.dataguardians.protobuf.Session.Trigger.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        action_ = 0;

        description_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.dataguardians.protobuf.Session.internal_static_io_dataguardians_protobuf_Trigger_descriptor;
      }

      @java.lang.Override
      public io.dataguardians.protobuf.Session.Trigger getDefaultInstanceForType() {
        return io.dataguardians.protobuf.Session.Trigger.getDefaultInstance();
      }

      @java.lang.Override
      public io.dataguardians.protobuf.Session.Trigger build() {
        io.dataguardians.protobuf.Session.Trigger result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.dataguardians.protobuf.Session.Trigger buildPartial() {
        io.dataguardians.protobuf.Session.Trigger result = new io.dataguardians.protobuf.Session.Trigger(this);
        result.action_ = action_;
        result.description_ = description_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.dataguardians.protobuf.Session.Trigger) {
          return mergeFrom((io.dataguardians.protobuf.Session.Trigger)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.dataguardians.protobuf.Session.Trigger other) {
        if (other == io.dataguardians.protobuf.Session.Trigger.getDefaultInstance()) return this;
        if (other.action_ != 0) {
          setActionValue(other.getActionValue());
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.dataguardians.protobuf.Session.Trigger parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.dataguardians.protobuf.Session.Trigger) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int action_ = 0;
      /**
       * <code>.io.dataguardians.protobuf.TriggerAction action = 1;</code>
       * @return The enum numeric value on the wire for action.
       */
      @java.lang.Override public int getActionValue() {
        return action_;
      }
      /**
       * <code>.io.dataguardians.protobuf.TriggerAction action = 1;</code>
       * @param value The enum numeric value on the wire for action to set.
       * @return This builder for chaining.
       */
      public Builder setActionValue(int value) {
        
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.io.dataguardians.protobuf.TriggerAction action = 1;</code>
       * @return The action.
       */
      @java.lang.Override
      public io.dataguardians.protobuf.Session.TriggerAction getAction() {
        @SuppressWarnings("deprecation")
        io.dataguardians.protobuf.Session.TriggerAction result = io.dataguardians.protobuf.Session.TriggerAction.valueOf(action_);
        return result == null ? io.dataguardians.protobuf.Session.TriggerAction.UNRECOGNIZED : result;
      }
      /**
       * <code>.io.dataguardians.protobuf.TriggerAction action = 1;</code>
       * @param value The action to set.
       * @return This builder for chaining.
       */
      public Builder setAction(io.dataguardians.protobuf.Session.TriggerAction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        action_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.io.dataguardians.protobuf.TriggerAction action = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAction() {
        
        action_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 2;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 2;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 2;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 2;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.dataguardians.protobuf.Trigger)
    }

    // @@protoc_insertion_point(class_scope:io.dataguardians.protobuf.Trigger)
    private static final io.dataguardians.protobuf.Session.Trigger DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.dataguardians.protobuf.Session.Trigger();
    }

    public static io.dataguardians.protobuf.Session.Trigger getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Trigger>
        PARSER = new com.google.protobuf.AbstractParser<Trigger>() {
      @java.lang.Override
      public Trigger parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Trigger(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Trigger> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Trigger> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.dataguardians.protobuf.Session.Trigger getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TerminalMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.dataguardians.protobuf.TerminalMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string sessionId = 1;</code>
     * @return The sessionId.
     */
    java.lang.String getSessionId();
    /**
     * <code>string sessionId = 1;</code>
     * @return The bytes for sessionId.
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();

    /**
     * <code>.io.dataguardians.protobuf.MessageType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.io.dataguardians.protobuf.MessageType type = 2;</code>
     * @return The type.
     */
    io.dataguardians.protobuf.Session.MessageType getType();

    /**
     * <code>.io.dataguardians.protobuf.Trigger trigger = 3;</code>
     * @return Whether the trigger field is set.
     */
    boolean hasTrigger();
    /**
     * <code>.io.dataguardians.protobuf.Trigger trigger = 3;</code>
     * @return The trigger.
     */
    io.dataguardians.protobuf.Session.Trigger getTrigger();
    /**
     * <code>.io.dataguardians.protobuf.Trigger trigger = 3;</code>
     */
    io.dataguardians.protobuf.Session.TriggerOrBuilder getTriggerOrBuilder();

    /**
     * <code>double keycode = 4;</code>
     * @return The keycode.
     */
    double getKeycode();

    /**
     * <code>string command = 5;</code>
     * @return The command.
     */
    java.lang.String getCommand();
    /**
     * <code>string command = 5;</code>
     * @return The bytes for command.
     */
    com.google.protobuf.ByteString
        getCommandBytes();
  }
  /**
   * Protobuf type {@code io.dataguardians.protobuf.TerminalMessage}
   */
  public static final class TerminalMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.dataguardians.protobuf.TerminalMessage)
      TerminalMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TerminalMessage.newBuilder() to construct.
    private TerminalMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TerminalMessage() {
      sessionId_ = "";
      type_ = 0;
      command_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TerminalMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TerminalMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              sessionId_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 26: {
              io.dataguardians.protobuf.Session.Trigger.Builder subBuilder = null;
              if (trigger_ != null) {
                subBuilder = trigger_.toBuilder();
              }
              trigger_ = input.readMessage(io.dataguardians.protobuf.Session.Trigger.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(trigger_);
                trigger_ = subBuilder.buildPartial();
              }

              break;
            }
            case 33: {

              keycode_ = input.readDouble();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              command_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.dataguardians.protobuf.Session.internal_static_io_dataguardians_protobuf_TerminalMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.dataguardians.protobuf.Session.internal_static_io_dataguardians_protobuf_TerminalMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.dataguardians.protobuf.Session.TerminalMessage.class, io.dataguardians.protobuf.Session.TerminalMessage.Builder.class);
    }

    public static final int SESSIONID_FIELD_NUMBER = 1;
    private volatile java.lang.Object sessionId_;
    /**
     * <code>string sessionId = 1;</code>
     * @return The sessionId.
     */
    @java.lang.Override
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      }
    }
    /**
     * <code>string sessionId = 1;</code>
     * @return The bytes for sessionId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>.io.dataguardians.protobuf.MessageType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.io.dataguardians.protobuf.MessageType type = 2;</code>
     * @return The type.
     */
    @java.lang.Override public io.dataguardians.protobuf.Session.MessageType getType() {
      @SuppressWarnings("deprecation")
      io.dataguardians.protobuf.Session.MessageType result = io.dataguardians.protobuf.Session.MessageType.valueOf(type_);
      return result == null ? io.dataguardians.protobuf.Session.MessageType.UNRECOGNIZED : result;
    }

    public static final int TRIGGER_FIELD_NUMBER = 3;
    private io.dataguardians.protobuf.Session.Trigger trigger_;
    /**
     * <code>.io.dataguardians.protobuf.Trigger trigger = 3;</code>
     * @return Whether the trigger field is set.
     */
    @java.lang.Override
    public boolean hasTrigger() {
      return trigger_ != null;
    }
    /**
     * <code>.io.dataguardians.protobuf.Trigger trigger = 3;</code>
     * @return The trigger.
     */
    @java.lang.Override
    public io.dataguardians.protobuf.Session.Trigger getTrigger() {
      return trigger_ == null ? io.dataguardians.protobuf.Session.Trigger.getDefaultInstance() : trigger_;
    }
    /**
     * <code>.io.dataguardians.protobuf.Trigger trigger = 3;</code>
     */
    @java.lang.Override
    public io.dataguardians.protobuf.Session.TriggerOrBuilder getTriggerOrBuilder() {
      return getTrigger();
    }

    public static final int KEYCODE_FIELD_NUMBER = 4;
    private double keycode_;
    /**
     * <code>double keycode = 4;</code>
     * @return The keycode.
     */
    @java.lang.Override
    public double getKeycode() {
      return keycode_;
    }

    public static final int COMMAND_FIELD_NUMBER = 5;
    private volatile java.lang.Object command_;
    /**
     * <code>string command = 5;</code>
     * @return The command.
     */
    @java.lang.Override
    public java.lang.String getCommand() {
      java.lang.Object ref = command_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        command_ = s;
        return s;
      }
    }
    /**
     * <code>string command = 5;</code>
     * @return The bytes for command.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCommandBytes() {
      java.lang.Object ref = command_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        command_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSessionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sessionId_);
      }
      if (type_ != io.dataguardians.protobuf.Session.MessageType.HEARTBEAT.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (trigger_ != null) {
        output.writeMessage(3, getTrigger());
      }
      if (keycode_ != 0D) {
        output.writeDouble(4, keycode_);
      }
      if (!getCommandBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, command_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSessionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sessionId_);
      }
      if (type_ != io.dataguardians.protobuf.Session.MessageType.HEARTBEAT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (trigger_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getTrigger());
      }
      if (keycode_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, keycode_);
      }
      if (!getCommandBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, command_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.dataguardians.protobuf.Session.TerminalMessage)) {
        return super.equals(obj);
      }
      io.dataguardians.protobuf.Session.TerminalMessage other = (io.dataguardians.protobuf.Session.TerminalMessage) obj;

      if (!getSessionId()
          .equals(other.getSessionId())) return false;
      if (type_ != other.type_) return false;
      if (hasTrigger() != other.hasTrigger()) return false;
      if (hasTrigger()) {
        if (!getTrigger()
            .equals(other.getTrigger())) return false;
      }
      if (java.lang.Double.doubleToLongBits(getKeycode())
          != java.lang.Double.doubleToLongBits(
              other.getKeycode())) return false;
      if (!getCommand()
          .equals(other.getCommand())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionId().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasTrigger()) {
        hash = (37 * hash) + TRIGGER_FIELD_NUMBER;
        hash = (53 * hash) + getTrigger().hashCode();
      }
      hash = (37 * hash) + KEYCODE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getKeycode()));
      hash = (37 * hash) + COMMAND_FIELD_NUMBER;
      hash = (53 * hash) + getCommand().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.dataguardians.protobuf.Session.TerminalMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.dataguardians.protobuf.Session.TerminalMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.dataguardians.protobuf.Session.TerminalMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.dataguardians.protobuf.Session.TerminalMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.dataguardians.protobuf.Session.TerminalMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.dataguardians.protobuf.Session.TerminalMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.dataguardians.protobuf.Session.TerminalMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.dataguardians.protobuf.Session.TerminalMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.dataguardians.protobuf.Session.TerminalMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.dataguardians.protobuf.Session.TerminalMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.dataguardians.protobuf.Session.TerminalMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.dataguardians.protobuf.Session.TerminalMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.dataguardians.protobuf.Session.TerminalMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.dataguardians.protobuf.TerminalMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.dataguardians.protobuf.TerminalMessage)
        io.dataguardians.protobuf.Session.TerminalMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.dataguardians.protobuf.Session.internal_static_io_dataguardians_protobuf_TerminalMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.dataguardians.protobuf.Session.internal_static_io_dataguardians_protobuf_TerminalMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.dataguardians.protobuf.Session.TerminalMessage.class, io.dataguardians.protobuf.Session.TerminalMessage.Builder.class);
      }

      // Construct using io.dataguardians.protobuf.Session.TerminalMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sessionId_ = "";

        type_ = 0;

        if (triggerBuilder_ == null) {
          trigger_ = null;
        } else {
          trigger_ = null;
          triggerBuilder_ = null;
        }
        keycode_ = 0D;

        command_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.dataguardians.protobuf.Session.internal_static_io_dataguardians_protobuf_TerminalMessage_descriptor;
      }

      @java.lang.Override
      public io.dataguardians.protobuf.Session.TerminalMessage getDefaultInstanceForType() {
        return io.dataguardians.protobuf.Session.TerminalMessage.getDefaultInstance();
      }

      @java.lang.Override
      public io.dataguardians.protobuf.Session.TerminalMessage build() {
        io.dataguardians.protobuf.Session.TerminalMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.dataguardians.protobuf.Session.TerminalMessage buildPartial() {
        io.dataguardians.protobuf.Session.TerminalMessage result = new io.dataguardians.protobuf.Session.TerminalMessage(this);
        result.sessionId_ = sessionId_;
        result.type_ = type_;
        if (triggerBuilder_ == null) {
          result.trigger_ = trigger_;
        } else {
          result.trigger_ = triggerBuilder_.build();
        }
        result.keycode_ = keycode_;
        result.command_ = command_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.dataguardians.protobuf.Session.TerminalMessage) {
          return mergeFrom((io.dataguardians.protobuf.Session.TerminalMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.dataguardians.protobuf.Session.TerminalMessage other) {
        if (other == io.dataguardians.protobuf.Session.TerminalMessage.getDefaultInstance()) return this;
        if (!other.getSessionId().isEmpty()) {
          sessionId_ = other.sessionId_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasTrigger()) {
          mergeTrigger(other.getTrigger());
        }
        if (other.getKeycode() != 0D) {
          setKeycode(other.getKeycode());
        }
        if (!other.getCommand().isEmpty()) {
          command_ = other.command_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.dataguardians.protobuf.Session.TerminalMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.dataguardians.protobuf.Session.TerminalMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object sessionId_ = "";
      /**
       * <code>string sessionId = 1;</code>
       * @return The sessionId.
       */
      public java.lang.String getSessionId() {
        java.lang.Object ref = sessionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sessionId = 1;</code>
       * @return The bytes for sessionId.
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        java.lang.Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sessionId = 1;</code>
       * @param value The sessionId to set.
       * @return This builder for chaining.
       */
      public Builder setSessionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sessionId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSessionId() {
        
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      /**
       * <code>string sessionId = 1;</code>
       * @param value The bytes for sessionId to set.
       * @return This builder for chaining.
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sessionId_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.io.dataguardians.protobuf.MessageType type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.io.dataguardians.protobuf.MessageType type = 2;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.io.dataguardians.protobuf.MessageType type = 2;</code>
       * @return The type.
       */
      @java.lang.Override
      public io.dataguardians.protobuf.Session.MessageType getType() {
        @SuppressWarnings("deprecation")
        io.dataguardians.protobuf.Session.MessageType result = io.dataguardians.protobuf.Session.MessageType.valueOf(type_);
        return result == null ? io.dataguardians.protobuf.Session.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.io.dataguardians.protobuf.MessageType type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(io.dataguardians.protobuf.Session.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.io.dataguardians.protobuf.MessageType type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private io.dataguardians.protobuf.Session.Trigger trigger_;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.dataguardians.protobuf.Session.Trigger, io.dataguardians.protobuf.Session.Trigger.Builder, io.dataguardians.protobuf.Session.TriggerOrBuilder> triggerBuilder_;
      /**
       * <code>.io.dataguardians.protobuf.Trigger trigger = 3;</code>
       * @return Whether the trigger field is set.
       */
      public boolean hasTrigger() {
        return triggerBuilder_ != null || trigger_ != null;
      }
      /**
       * <code>.io.dataguardians.protobuf.Trigger trigger = 3;</code>
       * @return The trigger.
       */
      public io.dataguardians.protobuf.Session.Trigger getTrigger() {
        if (triggerBuilder_ == null) {
          return trigger_ == null ? io.dataguardians.protobuf.Session.Trigger.getDefaultInstance() : trigger_;
        } else {
          return triggerBuilder_.getMessage();
        }
      }
      /**
       * <code>.io.dataguardians.protobuf.Trigger trigger = 3;</code>
       */
      public Builder setTrigger(io.dataguardians.protobuf.Session.Trigger value) {
        if (triggerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          trigger_ = value;
          onChanged();
        } else {
          triggerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.io.dataguardians.protobuf.Trigger trigger = 3;</code>
       */
      public Builder setTrigger(
          io.dataguardians.protobuf.Session.Trigger.Builder builderForValue) {
        if (triggerBuilder_ == null) {
          trigger_ = builderForValue.build();
          onChanged();
        } else {
          triggerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.io.dataguardians.protobuf.Trigger trigger = 3;</code>
       */
      public Builder mergeTrigger(io.dataguardians.protobuf.Session.Trigger value) {
        if (triggerBuilder_ == null) {
          if (trigger_ != null) {
            trigger_ =
              io.dataguardians.protobuf.Session.Trigger.newBuilder(trigger_).mergeFrom(value).buildPartial();
          } else {
            trigger_ = value;
          }
          onChanged();
        } else {
          triggerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.io.dataguardians.protobuf.Trigger trigger = 3;</code>
       */
      public Builder clearTrigger() {
        if (triggerBuilder_ == null) {
          trigger_ = null;
          onChanged();
        } else {
          trigger_ = null;
          triggerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.io.dataguardians.protobuf.Trigger trigger = 3;</code>
       */
      public io.dataguardians.protobuf.Session.Trigger.Builder getTriggerBuilder() {
        
        onChanged();
        return getTriggerFieldBuilder().getBuilder();
      }
      /**
       * <code>.io.dataguardians.protobuf.Trigger trigger = 3;</code>
       */
      public io.dataguardians.protobuf.Session.TriggerOrBuilder getTriggerOrBuilder() {
        if (triggerBuilder_ != null) {
          return triggerBuilder_.getMessageOrBuilder();
        } else {
          return trigger_ == null ?
              io.dataguardians.protobuf.Session.Trigger.getDefaultInstance() : trigger_;
        }
      }
      /**
       * <code>.io.dataguardians.protobuf.Trigger trigger = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.dataguardians.protobuf.Session.Trigger, io.dataguardians.protobuf.Session.Trigger.Builder, io.dataguardians.protobuf.Session.TriggerOrBuilder> 
          getTriggerFieldBuilder() {
        if (triggerBuilder_ == null) {
          triggerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.dataguardians.protobuf.Session.Trigger, io.dataguardians.protobuf.Session.Trigger.Builder, io.dataguardians.protobuf.Session.TriggerOrBuilder>(
                  getTrigger(),
                  getParentForChildren(),
                  isClean());
          trigger_ = null;
        }
        return triggerBuilder_;
      }

      private double keycode_ ;
      /**
       * <code>double keycode = 4;</code>
       * @return The keycode.
       */
      @java.lang.Override
      public double getKeycode() {
        return keycode_;
      }
      /**
       * <code>double keycode = 4;</code>
       * @param value The keycode to set.
       * @return This builder for chaining.
       */
      public Builder setKeycode(double value) {
        
        keycode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double keycode = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearKeycode() {
        
        keycode_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object command_ = "";
      /**
       * <code>string command = 5;</code>
       * @return The command.
       */
      public java.lang.String getCommand() {
        java.lang.Object ref = command_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          command_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string command = 5;</code>
       * @return The bytes for command.
       */
      public com.google.protobuf.ByteString
          getCommandBytes() {
        java.lang.Object ref = command_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          command_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string command = 5;</code>
       * @param value The command to set.
       * @return This builder for chaining.
       */
      public Builder setCommand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string command = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCommand() {
        
        command_ = getDefaultInstance().getCommand();
        onChanged();
        return this;
      }
      /**
       * <code>string command = 5;</code>
       * @param value The bytes for command to set.
       * @return This builder for chaining.
       */
      public Builder setCommandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        command_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.dataguardians.protobuf.TerminalMessage)
    }

    // @@protoc_insertion_point(class_scope:io.dataguardians.protobuf.TerminalMessage)
    private static final io.dataguardians.protobuf.Session.TerminalMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.dataguardians.protobuf.Session.TerminalMessage();
    }

    public static io.dataguardians.protobuf.Session.TerminalMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TerminalMessage>
        PARSER = new com.google.protobuf.AbstractParser<TerminalMessage>() {
      @java.lang.Override
      public TerminalMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TerminalMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TerminalMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TerminalMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.dataguardians.protobuf.Session.TerminalMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_dataguardians_protobuf_Trigger_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_dataguardians_protobuf_Trigger_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_dataguardians_protobuf_TerminalMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_dataguardians_protobuf_TerminalMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034src/main/proto/session.proto\022\031io.datag" +
      "uardians.protobuf\"X\n\007Trigger\0228\n\006action\030\001" +
      " \001(\0162(.io.dataguardians.protobuf.Trigger" +
      "Action\022\023\n\013description\030\002 \001(\t\"\261\001\n\017Terminal" +
      "Message\022\021\n\tsessionId\030\001 \001(\t\0224\n\004type\030\002 \001(\016" +
      "2&.io.dataguardians.protobuf.MessageType" +
      "\0223\n\007trigger\030\003 \001(\0132\".io.dataguardians.pro" +
      "tobuf.Trigger\022\017\n\007keycode\030\004 \001(\001\022\017\n\007comman" +
      "d\030\005 \001(\t*\261\001\n\rTriggerAction\022\r\n\tNO_ACTION\020\000" +
      "\022\016\n\nLOG_ACTION\020\001\022\020\n\014ALERT_ACTION\020\002\022\017\n\013WA" +
      "RN_ACTION\020\003\022\017\n\013DENY_ACTION\020\004\022\016\n\nJIT_ACTI" +
      "ON\020\005\022\021\n\rRECORD_ACTION\020\006\022\022\n\016APPROVE_ACTIO" +
      "N\020\007\022\026\n\022PERSISTENT_MESSAGE\020\010*+\n\013MessageTy" +
      "pe\022\r\n\tHEARTBEAT\020\000\022\r\n\tUSER_DATA\020\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_dataguardians_protobuf_Trigger_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_dataguardians_protobuf_Trigger_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_dataguardians_protobuf_Trigger_descriptor,
        new java.lang.String[] { "Action", "Description", });
    internal_static_io_dataguardians_protobuf_TerminalMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_dataguardians_protobuf_TerminalMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_dataguardians_protobuf_TerminalMessage_descriptor,
        new java.lang.String[] { "SessionId", "Type", "Trigger", "Keycode", "Command", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
