ALTER TABLE SYSTEM_RULES
DROP CONSTRAINT CONSTRAINT_AC1;

ALTER TABLE SYSTEM_RULES
    ADD CONSTRAINT CONSTRAINT_AC1
        FOREIGN KEY (RULE_ID)
            REFERENCES RULES(ID)
            ON DELETE CASCADE;