package io.sentrius.agent.analysis.agents.verbs;

import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import io.sentrius.agent.analysis.agents.agents.AgentConfig;
import io.sentrius.agent.analysis.agents.agents.PromptBuilder;
import io.sentrius.agent.analysis.agents.agents.VerbRegistry;
import io.sentrius.agent.analysis.agents.interpreters.ObjectListInterpreter;
import io.sentrius.sso.core.dto.JITTrackerDTO;
import io.sentrius.sso.core.dto.ztat.AtatRequest;
import io.sentrius.sso.core.exceptions.ZtatException;
import io.sentrius.sso.core.model.verbs.Verb;
import io.sentrius.sso.core.services.agents.AgentClientService;
import io.sentrius.sso.core.services.agents.LLMService;
import io.sentrius.sso.core.services.agents.ZeroTrustClientService;
import io.sentrius.sso.core.utils.JsonUtil;
import io.sentrius.sso.genai.Message;
import io.sentrius.sso.genai.Response;
import io.sentrius.sso.genai.model.ChatRequest;
import lombok.extern.slf4j.Slf4j;
import org.glassfish.jaxb.core.v2.model.core.TypeRef;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

/**
 * The `AgentVerbs` class provides implementations for various agent-related verbs.
 * These verbs interact with AI models and configurations to perform tasks such as
 * prompting agents, justifying operations, and assessing data.
 */
@Service
@Slf4j
public class AgentVerbs {

    final ZeroTrustClientService zeroTrustClientService;
    final LLMService llmService;
    final VerbRegistry verbRegistry;
    final AgentClientService agentClientService;

    @Value("${agent.ai.config:assessor-config.yaml}")
    private String agentConfigFile;

    final ObjectMapper mapper = new ObjectMapper(new YAMLFactory()); // Jackson ObjectMapper for YAML parsing

    /**
     * Constructs an `AgentVerbs` instance with the required services and registry.
     *
     * @param zeroTrustClientService The service for Zero Trust client interactions.
     * @param llmService The service for interacting with the LLM (Large Language Model).
     * @param verbRegistry The registry containing available verbs and their metadata.
     * @throws JsonProcessingException If there is an error processing JSON during initialization.
     */
    public AgentVerbs(ZeroTrustClientService zeroTrustClientService, LLMService llmService, VerbRegistry verbRegistry,
                      AgentClientService agentService
    ) throws JsonProcessingException {
        this.zeroTrustClientService = zeroTrustClientService;
        this.llmService = llmService;
        this.verbRegistry = verbRegistry;
        this.agentClientService = agentService;

        log.info("Loading agent config from {}", agentConfigFile);
    }

    /**
     * Prompts the agent for workload based on the provided arguments.
     *
     * @param args A map of arguments to customize the prompt.
     * @return An `ArrayNode` containing the plan generated by the agent.
     * @throws ZtatException If there is an error during the operation.
     * @throws IOException If there is an error reading the configuration file.
     */
    @Verb(name = "prompt_agent", returnType = ArrayNode.class, description = "Prompts for agent workload.", isAiCallable = false)
    public ArrayNode promptAgent(Map<String, Object> args) throws ZtatException, IOException {
        InputStream is = getClass().getClassLoader().getResourceAsStream(agentConfigFile);
        if (is == null) {
            throw new RuntimeException("assessor-config.yaml not found on classpath");
        }
        AgentConfig config = new ObjectMapper(new YAMLFactory()).readValue(is, AgentConfig.class);

        log.info("Agent config loaded: {}", config);
        PromptBuilder promptBuilder = new PromptBuilder(verbRegistry, config);
        var prompt = promptBuilder.buildPrompt();
        List<Message> messages = new ArrayList<>();

        messages.add(Message.builder().role("system").content(prompt).build());

        ChatRequest chatRequest = ChatRequest.builder().model("gpt-3.5-turbo").messages(messages).build();
        var resp = llmService.askQuestion(chatRequest);
        Response response = JsonUtil.MAPPER.readValue(resp, Response.class);
        log.info("Response is {}", resp);
        for (Response.Choice choice : response.getChoices()) {
            var content = choice.getMessage().getContent();
            log.info("content is {}", content);
            if (null != content && !content.isEmpty()) {
                JsonNode node = JsonUtil.MAPPER.readTree(content);
                log.info("Node is {}", node);
                if (node.get("plan") != null) {
                    ArrayNode plan = (ArrayNode) node.get("plan");
                    log.info("Plan is {}", plan);
                    return plan;
                }
            }
        }
        log.info("ahhh");
        return JsonUtil.MAPPER.createArrayNode();
    }

    /**
     * Chats with an agent to justify operations based on the provided arguments.
     *
     * @param args A map of arguments to customize the justification process.
     * @return A string response from the agent.
     * @throws ZtatException If there is an error during the operation.
     * @throws IOException If there is an error reading the configuration file.
     */
    @Verb(name = "justify_operations", description = "Chats with an agent to justify operations.", isAiCallable = false)
    public String justifyAgent(Map<String, Object> args) throws ZtatException, IOException {
        InputStream is = getClass().getClassLoader().getResourceAsStream(agentConfigFile);
        if (is == null) {
            throw new RuntimeException("assessor-config.yaml not found on classpath");
        }
        AgentConfig config = new ObjectMapper(new YAMLFactory()).readValue(is, AgentConfig.class);

        log.info("Agent config loaded: {}", config);
        PromptBuilder promptBuilder = new PromptBuilder(verbRegistry, config);
        var prompt = promptBuilder.buildPrompt();
        List<Message> messages = new ArrayList<>();

        messages.add(Message.builder().role("system").content(prompt).build());

        ChatRequest chatRequest = ChatRequest.builder().model("gpt-4o").messages(messages).build();

        return llmService.askQuestion(chatRequest);
    }

    /**
     * Assesses data based on the provided object list and the agent's context.
     *
     * @param objectList A list of objects to be assessed.
     * @return An `ArrayNode` containing the assessment results.
     * @throws ZtatException If there is an error during the operation.
     * @throws IOException If there is an error reading the configuration file.
     */
    @Verb(name = "assess_data", returnType = ArrayNode.class, description = "Accepts data based on the plan and seeks to perform the assessment outlined by the context.", inputInterpreter = ObjectListInterpreter.class)
    public ArrayNode assessData(List<?> objectList) throws ZtatException, IOException {
        InputStream is = getClass().getClassLoader().getResourceAsStream(agentConfigFile);
        if (is == null) {
            throw new RuntimeException("assessor-config.yaml not found on classpath");
        }
        AgentConfig config = new ObjectMapper(new YAMLFactory()).readValue(is, AgentConfig.class);

        log.info("Agent config loaded: {}", config);

        log.info("Object list is {}", objectList);
        for (var obj : objectList) {
            List<Message> messages = new ArrayList<>();
            var context = config.getContext();

            messages.add(Message.builder().role("user").content(obj.toString()).build());
            messages.add(Message.builder().role("system").content(context).build());

            ChatRequest chatRequest = ChatRequest.builder().model("gpt-4o").messages(messages).build();
            var resp = llmService.askQuestion(chatRequest);
            Response response = JsonUtil.MAPPER.readValue(resp, Response.class);
            log.info("Response is {}", resp);
            for (Response.Choice choice : response.getChoices()) {
                var content = choice.getMessage().getContent();
                log.info("content is {}", content);
            }
            log.info("Object is {}", obj);
        }
        return JsonUtil.MAPPER.createArrayNode();
    }

    @Verb(name = "get_work_requests", returnType = ArrayNode.class, description = "Queries the API for work " +
        "interacting with another agent")
    public List<AtatRequest> getWork() throws ZtatException, IOException {
        List<AtatRequest> requests = new ArrayList<>();

        var atatRequests = agentClientService.getAtatRequests();
        List<JITTrackerDTO> dtos =  JsonUtil.MAPPER.readValue(atatRequests, new TypeReference<>() {
        });
        /*
        for (var dto : dtos) {
            var request = new AtatRequest();
            request.setRequestId(dto.getId().toString());
            request.set
            request.setStatus(dto.getStatus());
            request.setCreatedAt(dto.getCreatedAt());
            request.setUpdatedAt(dto.getUpdatedAt());
            request.setAgentId(dto.getAgentId());
            requests.add(request);
        }*/


        return requests;
    }
}