package io.sentrius.agent.analysis.agents.verbs;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.ListIterator;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import io.sentrius.agent.analysis.agents.agents.AgentConfig;
import io.sentrius.agent.analysis.agents.agents.AgentVerb;
import io.sentrius.agent.analysis.agents.agents.PromptBuilder;
import io.sentrius.agent.analysis.agents.agents.VerbRegistry;
import io.sentrius.agent.analysis.model.TerminalResponse;
import io.sentrius.agent.analysis.model.WebSocky;
import io.sentrius.sso.core.dto.agents.AgentContextDTO;
import io.sentrius.sso.core.dto.capabilities.EndpointDescriptor;
import io.sentrius.sso.core.dto.ztat.AgentExecution;
import io.sentrius.sso.core.exceptions.ZtatException;
import io.sentrius.sso.core.model.verbs.Verb;
import io.sentrius.sso.core.services.agents.AgentClientService;
import io.sentrius.sso.core.services.agents.AgentExecutionService;
import io.sentrius.sso.core.services.agents.LLMService;
import io.sentrius.sso.core.services.agents.ZeroTrustClientService;
import io.sentrius.sso.core.utils.JsonUtil;
import io.sentrius.sso.genai.Message;
import io.sentrius.sso.genai.Response;
import io.sentrius.sso.genai.model.LLMRequest;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

@Service
@Slf4j

public class ChatVerbs extends VerbBase{

    private final AgentExecutionService agentExecutionService;

    final ZeroTrustClientService zeroTrustClientService;
    final LLMService llmService;
    final VerbRegistry verbRegistry;
    final AgentClientService agentClientService;

    protected ChatVerbs(@Value("${agent.ai.config}") String agentConfigFile,
                        @Value("${agent.ai.context.db.id:none}") String agentDatabaseContext,
                        AgentClientService agentClientService, AgentExecutionService agentExecutionService,
                        ZeroTrustClientService zeroTrustClientService, LLMService llmService, VerbRegistry verbRegistry,
                        AgentClientService agentClientService1
    ) {
        super(agentConfigFile, agentDatabaseContext, agentClientService);
        this.agentExecutionService = agentExecutionService;
        this.zeroTrustClientService = zeroTrustClientService;
        this.llmService = llmService;
        this.verbRegistry = verbRegistry;
        this.agentClientService = agentClientService1;
    }

    /**
     * Prompts the agent for workload based on the provided arguments.
     *
     * @return An `ArrayNode` containing the plan generated by the agent.
     * @throws io.sentrius.sso.core.exceptions.ZtatException If there is an error during the operation.
     * @throws java.io.IOException If there is an error reading the configuration file.
     */
    @Verb(name = "interpret_user_request", returnType = ArrayNode.class, description = "Queries the LLM using the " +
        "user input.",
        isAiCallable = false, requiresTokenManagement = true)
    public TerminalResponse interpretUserData(
        AgentExecution execution, @NonNull WebSocky socketConnection,
        @NonNull Message userMessage) throws ZtatException,
        IOException {

        var lastMessage = socketConnection.getMessages().stream().reduce((prev, next) -> next).orElse(null);
        if (socketConnection.getMessages().isEmpty()) {

            InputStream terminalHelperStream = getClass().getClassLoader().getResourceAsStream("terminal-helper.json");
            if (terminalHelperStream == null) {
                throw new RuntimeException("assessor-config.yaml not found on classpath");

            }

            String terminalResponse = new String(terminalHelperStream.readAllBytes());

            AgentConfig config = getAgentConfig(execution);
            log.info("Agent config loaded: {}", config);
            PromptBuilder promptBuilder = new PromptBuilder(verbRegistry, config);
            var prompt = promptBuilder.buildPrompt(false
            );
            List<Message> messages = new ArrayList<>();
            var context = Message.builder().role("system").content(prompt).build();
            messages.add(context);

            messages.add(Message.builder().role("system").content("You have executed verbs for the previous user " +
                "messages. Please generate a user response that summarizes the last message.").build());
            int size = getMessageSize(context);

            var history = getContextWindow(execution.getMessages(), 1024*96 - (size));
            messages.addAll(history);
            messages.add(Message.builder().role("system").content("Please ensure your nextOperation abides by the " +
                "following json format and leave it empty if user's request doesn't require explicit use of system " +
                "operations" +
                ". Please summarize prior terminal " +
                "sessions, using " +
                "terminal output if needed " +
                "for clarity of the next LLM request and for the user. Ensure your all future responses meets this " +
                "json format (TerminalResponse format): " + terminalResponse).build());
            messages.add(Message.builder().role("user").content(userMessage.getContent()).build());
            LLMRequest chatRequest = LLMRequest.builder().model("gpt-4o-mini").messages(messages).build();
            var resp = llmService.askQuestion(execution, chatRequest);
            execution.addMessages( messages );
            Response response = JsonUtil.MAPPER.readValue(resp, Response.class);
            log.info("Response is {}", resp);
            for (Response.Choice choice : response.getChoices()) {
                var content = choice.getMessage().getContent();
                if (content.startsWith("```json")) {
                    content = content.substring(7, content.length() - 3);
                } else if (content.startsWith("```")) {
                    content = content.substring(3, content.length() - 3);
                }
                log.info("content is {}", content);
                if (null != content && !content.isEmpty()) {
                    try {
                        var newResponse = JsonUtil.MAPPER.enable(JsonParser.Feature.ALLOW_COMMENTS).readValue(
                            content,
                            TerminalResponse.class
                        );
                        return newResponse;
                    }catch (JsonParseException e) {
                        log.error("Failed to parse terminal response: {}", e.getMessage());
                        return TerminalResponse.builder().responseForUser(content).build();
                    }
                }
            }
        } else {
            InputStream terminalHelperStream = getClass().getClassLoader().getResourceAsStream("terminal-helper.json");
            if (terminalHelperStream == null) {
                throw new RuntimeException("assessor-config.yaml not found on classpath");

            }
            String terminalResponse = new String(terminalHelperStream.readAllBytes());

            AgentConfig config = getAgentConfig(execution);

            log.info("Agent config loaded: {}", config);
            PromptBuilder promptBuilder = new PromptBuilder(verbRegistry, config);
            var prompt = promptBuilder.buildPrompt(false);
            List<Message> messages = new ArrayList<>();
            //var context = Message.builder().role("system").content(prompt).build();
            //messages.add(context);

            /*
            var listedEndpoints = Message.builder().role("system").content("These are a list of available endpoints, " +
                "description," +
                " their " +
                "name:" + endpointArray).build();
            messages.add(listedEndpoints);
            messages.add(Message.builder().role("system").content("You have executed verbs for the previous user " +
                "messages. Please generate a user response that summarizes the last message.").build());
            int size = getMessageSize(context) + getMessageSize(listedEndpoints);

            var history = getContextWindow(execution.getMessages(), 1024*96 - (size));
            messages.addAll(history);

             */
            var history = getContextWindow(execution.getMessages(), 1024*96 );
            messages.addAll(history);

//            messages.add(Message.builder().role("assistant").content("prior response: " + lastMessage
//            .getTerminalSummaryForLLM()).build());

            execution.addMessages( userMessage );
            messages.add(Message.builder().role("user").content(userMessage.getContent()).build());

            LLMRequest chatRequest = LLMRequest.builder().model("gpt-4o-mini").messages(messages).build();
            var resp = llmService.askQuestion(execution, chatRequest);

            Response response = JsonUtil.MAPPER.readValue(resp, Response.class);
            log.info("Response is {}", resp);
            for (Response.Choice choice : response.getChoices()) {
                var content = choice.getMessage().getContent();
                if (content.startsWith("```json")) {
                    content = content.substring(7, content.length() - 3);
                } else if (content.startsWith("```")) {
                    content = content.substring(3, content.length() - 3);
                }
                log.info("content is {}", content);
                if (null != content && !content.isEmpty()) {

                    execution.addMessages( choice.getMessage() );
                    try {
                        var newResponse = JsonUtil.MAPPER.enable(JsonParser.Feature.ALLOW_COMMENTS).readValue(
                            content,
                            TerminalResponse.class
                        );
                        return newResponse;
                    }catch (JsonParseException e) {
                        log.error("Failed to parse terminal response: {}", e.getMessage());
                        return TerminalResponse.builder().responseForUser(content).terminalSummaryForLLM(lastMessage.getTerminalSummaryForLLM()).build();
                    }

                }
            }
        }

        return null;
    }

    public List<Message> getContextWindow(List<Message> allMessages, int maxContextSize) {
        List<Message> systemMessages = new ArrayList<>();
        List<Message> window = new ArrayList<>();
        int totalSize = 0;

        // First: collect system messages (or other required ones)
        for (Message msg : allMessages) {
            if ("system".equals(msg.role)) {
                systemMessages.add(msg);
                totalSize += getMessageSize(msg);
            }
        }

        // If system messages already exceed max context, return only those
        if (totalSize >= maxContextSize) {
            return systemMessages;
        }

        int remainingSize = maxContextSize - totalSize;

        // Then: collect non-system messages from the end, up to remainingSize
        ListIterator<Message> iter = allMessages.listIterator(allMessages.size());
        while (iter.hasPrevious()) {
            Message msg = iter.previous();

            if ("system".equals(msg.role)) continue; // already added

            int messageSize = getMessageSize(msg);
            if (messageSize > remainingSize) break;

            window.add(0, msg); // prepend
            remainingSize -= messageSize;
        }

        // Combine system + selected recent messages
        List<Message> result = new ArrayList<>();
        result.addAll(systemMessages);
        result.addAll(window);

        return result;
    }


    private int getMessageSize(Message msg) {
        int size = 0;
        if (msg.role != null) size += msg.role.length();
        if (msg.content != null) size += msg.content.length();
        if (msg.refusal != null) size += msg.refusal.length();
        return size;
    }

    public TerminalResponse interpret_plan_response(
        AgentExecution execution, @NonNull WebSocky socketConnection,
        AgentVerb agentVerb, String planExecutionOutput) throws ZtatException,
        IOException {


        log.info("interpret_plan_response");

        var lastMessage = socketConnection.getMessages().stream().reduce((prev, next) -> next).orElse(null);

            InputStream terminalHelperStream = getClass().getClassLoader().getResourceAsStream("terminal-helper.json");
            if (terminalHelperStream == null) {
                throw new RuntimeException("assessor-config.yaml not found on classpath");

            }
            String terminalResponse = new String(terminalHelperStream.readAllBytes());

            AgentConfig config = getAgentConfig(execution);

            log.info("Agent config loaded: {}", config);
            PromptBuilder promptBuilder = new PromptBuilder(verbRegistry, config);
            var prompt = promptBuilder.buildPrompt(false);
            List<Message> messages = new ArrayList<>();

            if (execution.getMessages().isEmpty()) {
                log.info("*** Adding Prompt");
                var context = Message.builder().role("system").content(prompt).build();
                messages.add(context);



                messages.add(Message.builder().role("system").content("You have executed verbs for the previous user " +
                    "messages. Please generate a user response that summarizes the last message. Keep all responses in " +
                    "TerminalResponse format" +
                    ".").build());
            }


            if (null != agentVerb) {
                messages.add(
                    Message.builder().role("system").content("You have executed verb: " + agentVerb.getName() +
                        " with the following description: " + agentVerb.getDescription()).build());
            }


            //messages.add(Message.builder().role("assistant").content("prior response: " + lastMessage
        // .getTerminalSummaryForLLM()).build());
            messages.add(Message.builder().role("assistant").content(planExecutionOutput).build());

            LLMRequest chatRequest = LLMRequest.builder().model("gpt-4o-mini").messages(messages).build();
            var resp = llmService.askQuestion(execution, chatRequest);
            execution.addMessages( messages );
            var history = getContextWindow(execution.getMessages(), 1024*96 );
            messages.addAll(history);
            Response response = JsonUtil.MAPPER.readValue(resp, Response.class);
            log.info("Response is {}", resp);
            for (Response.Choice choice : response.getChoices()) {
                var content = choice.getMessage().getContent();
                if (content.startsWith("```json")) {
                    content = content.substring(7, content.length() - 3);
                } else if (content.startsWith("```")) {
                    content = content.substring(3, content.length() - 3);
                }
                log.info("content is {}", content);
                if (null != content && !content.isEmpty()) {
                    try {
                        var newResponse = JsonUtil.MAPPER.enable(JsonParser.Feature.ALLOW_COMMENTS).readValue(
                            content,
                            TerminalResponse.class
                        );
                        return newResponse;
                    } catch (Exception e){
                        return TerminalResponse.builder().responseForUser(content).build();
                    }

                }
            }
        return null;
    }



}
