package io.sentrius.agent.analysis.agents.verbs;

import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import io.sentrius.agent.analysis.agents.agents.AgentConfig;
import io.sentrius.agent.analysis.agents.agents.AgentVerb;
import io.sentrius.agent.analysis.agents.agents.PromptBuilder;
import io.sentrius.agent.analysis.agents.agents.VerbRegistry;
import io.sentrius.agent.analysis.model.TerminalResponse;
import io.sentrius.agent.analysis.model.WebSocky;
import io.sentrius.sso.core.dto.ztat.AgentExecution;
import io.sentrius.sso.core.exceptions.ZtatException;
import io.sentrius.sso.core.model.verbs.Verb;
import io.sentrius.sso.core.services.agents.AgentClientService;
import io.sentrius.sso.core.services.agents.LLMService;
import io.sentrius.sso.core.services.agents.ZeroTrustClientService;
import io.sentrius.sso.core.utils.JsonUtil;
import io.sentrius.sso.genai.Message;
import io.sentrius.sso.genai.Response;
import io.sentrius.sso.genai.model.LLMRequest;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

@Service
@Slf4j
@RequiredArgsConstructor
public class ChatVerbs {

    @Value("${agent.ai.config}")
    private String agentConfigFile;

    final ZeroTrustClientService zeroTrustClientService;
    final LLMService llmService;
    final VerbRegistry verbRegistry;
    final AgentClientService agentClientService;

    /**
     * Prompts the agent for workload based on the provided arguments.
     *
     * @return An `ArrayNode` containing the plan generated by the agent.
     * @throws io.sentrius.sso.core.exceptions.ZtatException If there is an error during the operation.
     * @throws java.io.IOException If there is an error reading the configuration file.
     */
    @Verb(name = "interpret_user_request", returnType = ArrayNode.class, description = "Queries the LLM using the " +
        "user input.",
        isAiCallable = false, requiresTokenManagement = true)
    public TerminalResponse interpretUserData(
        AgentExecution execution, @NonNull WebSocky socketConnection,
        @NonNull Message userMessage) throws ZtatException,
        IOException {

        var lastMessage = socketConnection.getMessages().stream().reduce((prev, next) -> next).orElse(null);
        if (socketConnection.getMessages().isEmpty()) {

            InputStream terminalHelperStream = getClass().getClassLoader().getResourceAsStream("terminal-helper.json");
            if (terminalHelperStream == null) {
                throw new RuntimeException("assessor-config.yaml not found on classpath");

            }
            String terminalResponse = new String(terminalHelperStream.readAllBytes());
            InputStream is = getClass().getClassLoader().getResourceAsStream(agentConfigFile);
            if (is == null) {
                throw new RuntimeException(agentConfigFile +  " not found on classpath");
            }
            AgentConfig config = new ObjectMapper(new YAMLFactory()).readValue(is, AgentConfig.class);

            log.info("Agent config loaded: {}", config);
            PromptBuilder promptBuilder = new PromptBuilder(verbRegistry, config);
            var prompt = promptBuilder.buildPrompt();
            List<Message> messages = new ArrayList<>();

            messages.add(Message.builder().role("system").content(prompt).build());
            messages.add(Message.builder().role("system").content("Please ensure your nextOperation abides by the " +
                "following json format and leave it empty if user's request doesn't require explicit use of system " +
                "operations" +
                ". Please summarize prior terminal " +
                "sessions, using " +
                "terminal output if needed " +
                "for clarity of the next LLM request and for the user: " + terminalResponse).build());
            messages.add(Message.builder().role("user").content(userMessage.getContent()).build());
            LLMRequest chatRequest = LLMRequest.builder().model("gpt-4o").messages(messages).build();
            var resp = llmService.askQuestion(execution, chatRequest);
            execution.addMessages( messages );
            Response response = JsonUtil.MAPPER.readValue(resp, Response.class);
            log.info("Response is {}", resp);
            for (Response.Choice choice : response.getChoices()) {
                var content = choice.getMessage().getContent();
                if (content.startsWith("```json")) {
                    content = content.substring(7, content.length() - 3);
                } else if (content.startsWith("```")) {
                    content = content.substring(3, content.length() - 3);
                }
                log.info("content is {}", content);
                if (null != content && !content.isEmpty()) {
                    var newResponse =   JsonUtil.MAPPER.enable(JsonParser.Feature.ALLOW_COMMENTS).readValue(content,
                        TerminalResponse.class);
                    return newResponse;
                }
            }
        } else {
            InputStream terminalHelperStream = getClass().getClassLoader().getResourceAsStream("terminal-helper.json");
            if (terminalHelperStream == null) {
                throw new RuntimeException("assessor-config.yaml not found on classpath");

            }
            String terminalResponse = new String(terminalHelperStream.readAllBytes());
            InputStream is = getClass().getClassLoader().getResourceAsStream(agentConfigFile);
            if (is == null) {
                throw new RuntimeException(agentConfigFile +  " not found on classpath");
            }
            AgentConfig config = new ObjectMapper(new YAMLFactory()).readValue(is, AgentConfig.class);

            log.info("Agent config loaded: {}", config);
            PromptBuilder promptBuilder = new PromptBuilder(verbRegistry, config);
            var prompt = promptBuilder.buildPrompt();
            List<Message> messages = new ArrayList<>();

            messages.add(Message.builder().role("system").content(prompt).build());
            messages.add(Message.builder().role("system").content("Please ensure your nextOperation abide by the " +
                "following json format. Please summarize prior terminal sessions, using terminal output if needed " +
                "for clarity of the next LLM request and for the user: " + terminalResponse).build());
            messages.add(Message.builder().role("assistant").content("prior response: " + lastMessage.getTerminalSummaryForLLM()).build());
            messages.add(Message.builder().role("user").content(userMessage.getContent()).build());

            LLMRequest chatRequest = LLMRequest.builder().model("gpt-4o").messages(messages).build();
            var resp = llmService.askQuestion(execution, chatRequest);
            execution.addMessages( messages );
            Response response = JsonUtil.MAPPER.readValue(resp, Response.class);
            log.info("Response is {}", resp);
            for (Response.Choice choice : response.getChoices()) {
                var content = choice.getMessage().getContent();
                if (content.startsWith("```json")) {
                    content = content.substring(7, content.length() - 3);
                } else if (content.startsWith("```")) {
                    content = content.substring(3, content.length() - 3);
                }
                log.info("content is {}", content);
                if (null != content && !content.isEmpty()) {
                    var newResponse =   JsonUtil.MAPPER.enable(JsonParser.Feature.ALLOW_COMMENTS).readValue(content,
                        TerminalResponse.class);
                    return newResponse;
                }
            }
        }

        return null;
    }


    public TerminalResponse interpret_plan_response(
        AgentExecution execution, @NonNull WebSocky socketConnection,
        AgentVerb agentVerb, String planExecutionOutput) throws ZtatException,
        IOException {


        log.info("interpret_plan_response");

        var lastMessage = socketConnection.getMessages().stream().reduce((prev, next) -> next).orElse(null);

            InputStream terminalHelperStream = getClass().getClassLoader().getResourceAsStream("terminal-helper.json");
            if (terminalHelperStream == null) {
                throw new RuntimeException("assessor-config.yaml not found on classpath");

            }
            String terminalResponse = new String(terminalHelperStream.readAllBytes());
            InputStream is = getClass().getClassLoader().getResourceAsStream(agentConfigFile);
            if (is == null) {
                throw new RuntimeException(agentConfigFile +  " not found on classpath");
            }
            AgentConfig config = new ObjectMapper(new YAMLFactory()).readValue(is, AgentConfig.class);

            log.info("Agent config loaded: {}", config);
            PromptBuilder promptBuilder = new PromptBuilder(verbRegistry, config);
            var prompt = promptBuilder.buildPrompt();
            List<Message> messages = new ArrayList<>();

            messages.add(Message.builder().role("system").content(prompt).build());
            messages.add(Message.builder().role("system").content("You have executed verbs for the previous user " +
                "messages. Please generate a user response that summarizes the last message.").build());
            if (null != agentVerb ){
                messages.add(Message.builder().role("system").content("You have executed verb: " + agentVerb.getName() +
                    " with the following description: " + agentVerb.getDescription()).build());
            }
            messages.add(Message.builder().role("assistant").content("prior response: " + lastMessage.getTerminalSummaryForLLM()).build());
            messages.add(Message.builder().role("assistant").content(planExecutionOutput).build());

            LLMRequest chatRequest = LLMRequest.builder().model("gpt-4o").messages(messages).build();
            var resp = llmService.askQuestion(execution, chatRequest);
            execution.addMessages( messages );
            Response response = JsonUtil.MAPPER.readValue(resp, Response.class);
            log.info("Response is {}", resp);
            for (Response.Choice choice : response.getChoices()) {
                var content = choice.getMessage().getContent();
                if (content.startsWith("```json")) {
                    content = content.substring(7, content.length() - 3);
                } else if (content.startsWith("```")) {
                    content = content.substring(3, content.length() - 3);
                }
                log.info("content is {}", content);
                if (null != content && !content.isEmpty()) {
                    var newResponse =   JsonUtil.MAPPER.enable(JsonParser.Feature.ALLOW_COMMENTS).readValue(content,
                        TerminalResponse.class);
                    return newResponse;
                }
            }
        return null;
    }
}
