# General settings
replicaCount: 1
namespace: default


tenant: sentrius-demo
subdomain: "{{ .Values.tenant }}.sentrius.cloud"

# Sentrius configuration
sentrius:
  image:
    repository: us-central1-docker.pkg.dev/sentrius-project/sentrius-repo
    tag: tag
    pullPolicy: IfNotPresent
  port: 8080
  ssh:
    port: 22
  env:
    SPRING_DATASOURCE_USERNAME: admin
    SPRING_DATASOURCE_PASSWORD: password
    KEYSTORE_PASSWORD: sentrius
  resources: {}
  oauth2:
    client_id: sentrius-api
    client_secret: nGkEukexSWTvDzYjSkDmeUlM0FJ5Jhh0
    authorization_grant_type: authorization_code
    redirect_uri: http://{{ .Values.subdomain }}/login/oauth2/code/keycloak
    scope: openid,profile,email
    issuer_uri: http://keycloak.{{ .Values.subdomain }}/realms/sentrius

sentriusagent:
  service:
    type: NodePort
    nodePort: 30083
  image:
    repository: sentrius-agent
    pullPolicy: IfNotPresent
  port: 8080
  oauth2:
    client_id: sentrius-api
    client_secret: nGkEukexSWTvDzYjSkDmeUlM0FJ5Jhh0
    authorization_grant_type: authorization_code
    redirect-uri: http://{{ .Values.subdomain }}/login/oauth2/code/keycloak
    scope: openid,profile,email
    issuer-uri: http://keycloak.{{ .Values.subdomain }}/realms/sentrius
  ssh:
    port: 22
  env:
    SPRING_DATASOURCE_USERNAME: admin
    SPRING_DATASOURCE_PASSWORD: password
    KEYSTORE_PASSWORD: sentrius
  resources: {}
  config:
    application: |
      

# PostgreSQL configuration
postgres:
  image:
    repository: postgres
    tag: 15
  port: 5432
  storageSize: 10Gi
  env:
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: password
    POSTGRES_DB: sentrius

ssh:
  image:
    repository: sentrius-ssh
    pullPolicy: IfNotPresent
  port: 22
  env:
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: password
    POSTGRES_DB: sentrius

# Secrets
secrets:
  db:
    username: YWRtaW4=       # admin
    password: cGFzc3dvcmQ=   # password
    keystorePassword: c2VudHJpdXM= # sentrius

keycloak:
  image:
    repository: sentrius-keycloak
    pullPolicy: IfNotPresent
  host: keycloak.default.svc.cluster.local
  adminUser: admin
  adminPassword: admin
  port: 8081
  clientId: sentrius-api
  clientSecret: nGkEukexSWTvDzYjSkDmeUlM0FJ5Jhh0
  db:
    image: postgres:15
    user: keycloak
    password: password
    database: keycloak
    storageSize: 10Gi
  replicas: 1
  #hostname: sentrius-keycloak


