apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sentriusagent
spec:
  type: NodePort
  selector:
    app: sentriusagent
  ports:
    - protocol: TCP
      port: 80        # Port exposed to the outside world
      targetPort: {{ .Values.sentriusagent.port }} # Port used inside the container
      nodePort: {{ .Values.sentriusagent.service.nodePort | default 30083 }} # NodePort range: 30000-32767
