{{- if eq .Values.environment "gke" }}
# sentrius-backend-config.yaml
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  # This name MUST match the name used in your Service annotation
  name: agentproxy-backend-config
  namespace: {{ .Values.tenant }}
  annotations:
    helm.sh/resource-policy: keep # <--- Add this
spec:
  # Health check is required for GKE Ingress to work
  healthCheck:
    type: HTTP
    port: {{ .Values.agentproxy.port }} # Match the Service port
    requestPath: /actuator/health
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 2
{{- end }}