apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-agentproxy
  namespace: {{ .Values.tenant }}
  annotations:
    {{- if eq .Values.environment "gke" }}
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: |
      {
        "ports": {
          "http": "agentproxy-backend-config"
        }
      }
    {{- else if eq .Values.environment "aws" }}
    {{- range $key, $value := .Values.sentrius.annotations.aws }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
    {{- else if eq .Values.environment "azure" }}
    {{- range $key, $value := .Values.sentrius.annotations.azure }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
    {{- end }}
  labels:
    app: agentproxy
spec:
  type: {{ .Values.sentrius.serviceType }}
  ports:
    - name: http
      port: {{ .Values.sentrius.port }}
      targetPort: {{ .Values.sentrius.port }} # Port used inside the container
      {{- if eq .Values.sentrius.serviceType "NodePort" }}
      nodePort: {{ .Values.agentproxy.nodePort | default 30080  }}
      {{- end }}
  selector:
    app: agentproxy