apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sentriusaiagent
  namespace: {{ .Values.tenant }}
  annotations:
    {{- if eq .Values.environment "gke" }}
    cloud.google.com/backend-config: '{"default": "sentrius-backend-config"}'
    {{- else if eq .Values.environment "aws" }}
    {{- range $key, $value := .Values.sentrius.annotations.aws }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
    {{- else if eq .Values.environment "azure" }}
    {{- range $key, $value := .Values.sentrius.annotations.azure }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
    {{- end }}
spec:
  type: NodePort
  selector:
    app: sentriusaiagent
  ports:
    - protocol: TCP
      port: 80        # Port exposed to the outside world
      targetPort: {{ .Values.sentriusaiagent.port }} # Port used inside the container
      nodePort: {{ .Values.sentriusaiagent.service.nodePort | default 30085 }} # NodePort range: 30000-32767
