apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sentriusaiagent
  namespace: {{ .Values.tenant }}
  annotations:
    {{- if eq .Values.environment "gke" }}
    cloud.google.com/backend-config: '{"default": "sentrius-backend-config"}'
    {{- else if eq .Values.environment "aws" }}
    {{- range $key, $value := .Values.sentrius.annotations.aws }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
    {{- else if eq .Values.environment "azure" }}
    {{- range $key, $value := .Values.sentrius.annotations.azure }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
    {{- end }}
spec:
  type: {{ .Values.sentriusaiagent.service.type }}
  ports:
    - name: http
      port: {{ .Values.sentriusaiagent.port }}
      targetPort: {{ .Values.sentriusaiagent.port }} # Port used inside the container
      {{- if eq .Values.sentriusaiagent.service.type "NodePort" }}
      nodePort: {{ .Values.sentriusaiagent.nodePort | default 30085 }}
      {{- end }}
  selector:
    app: sentriusaiagent