{{- if .Values.config.usePVC }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-config-pvc
  labels:
    {{- include "sentrius.labels" . | nindent 4 }}
  annotations:
    description: "Configuration storage"
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.config.storageClassName }}
  storageClassName: {{ .Values.config.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.config.storageSize | default "1Gi" }}
{{- end }}
