apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sentrius
  labels:
    {{- include "sentrius.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sentrius
  template:
    metadata:
      labels:
        app: sentrius
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-postgres 5432; do echo waiting for postgres; sleep 2; done;' ]
      containers:
        - name: sentrius
          image: "{{ .Values.sentrius.image.repository }}:{{ .Values.sentrius.image.tag }}"
          imagePullPolicy: {{ .Values.sentrius.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.sentrius.port }}
          {{- if not (eq .Values.environment "gke") }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthCheck.readinessProbe.path }}
              port: {{ .Values.healthCheck.readinessProbe.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: {{ .Values.healthCheck.livenessProbe.path }}
              port: {{ .Values.healthCheck.livenessProbe.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /config
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: db-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: db-password
            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: keystore-password
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-config
