{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: managed-cert-ingress-{{ .Values.tenant }}
  namespace: {{ .Values.tenant }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.certificates.enabled }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- else }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    {{- end }}
spec:
  {{- if .Values.ingress.tlsEnabled }}
  tls:
    - hosts:
        - "{{ .Values.keycloakSubdomain }}"
        - "{{ .Values.subdomain }}"
      secretName: wildcard-cert-{{ .Values.tenant }}
  {{- end }}
  rules:
    - host: "{{ .Values.keycloakSubdomain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-keycloak
                port:
                  number: 8081
    - host: "{{ .Values.subdomain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-sentrius
                port:
                  number: 8080
{{- end }}
