apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-integrationproxy
  namespace: {{ .Values.tenant }}
  annotations:
      {{- if eq .Values.environment "gke" }}
    cloud.google.com/backend-config: |
      {
        "ports": {
          "http": "integrationproxy-backend-config"
        }
      }
      {{- else if eq .Values.environment "aws" }}
      {{- range $key, $value := .Values.sentrius.annotations.aws }}
      {{ $key }}: "{{ $value }}"
      {{- end }}
      {{- else if eq .Values.environment "azure" }}
      {{- range $key, $value := .Values.sentrius.annotations.azure }}
      {{ $key }}: "{{ $value }}"
      {{- end }}
      {{- end }}
  labels:
    app: integrationproxy
spec:
  type: {{ .Values.sentrius.serviceType }}
  ports:
    - name: http
      port: {{ .Values.sentrius.port }}
      targetPort: {{ .Values.sentrius.port }} # Port used inside the container
      {{- if eq .Values.sentrius.serviceType "NodePort" }}
      nodePort: {{ .Values.integrationproxy.nodePort | default 30080  }}
      {{- end }}
  selector:
    app: integrationproxy