{{- if .Values.jaeger.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: {{ .Values.tenant }}
  labels:
    app: jaeger
spec:
  selector:
    app: jaeger
  ports:
    - name: http-query
      port: 16686
      targetPort: 16686
    - name: grpc-otlp
      port: 4317
      targetPort: 4317
    - name: http-otlp
      port: 4318
      targetPort: 4318
{{- end }}
