{{- if .Values.kafka.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka
  namespace: {{ .Values.tenant }}
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - name: kafka
      port: 9092
      targetPort: {{ .Values.kafka.port }}
{{- end }}
