apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: {{ .Values.keycloak.replicas }}
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: {{ .Values.keycloak.image }}
          ports:
            - containerPort: 8180
          env:
            - name: KC_HTTP_PORT
              value: "8180"
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.keycloak.adminUser }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: {{ .Values.keycloak.adminPassword }}
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL_HOST
              value: keycloak-db
            - name: KC_DB_DATABASE
              value: {{ .Values.keycloak.db.database }}
            - name: KC_DB_USERNAME
              value: {{ .Values.keycloak.db.user }}
            - name: KC_DB_PASSWORD
              value: {{ .Values.keycloak.db.password }}
            - name: KC_HOSTNAME
              value: {{ .Values.keycloak.hostname }}
          command:
            - start-dev
            - --import-realm
          volumeMounts:
            - name: keycloak-realms
              mountPath: {{ .Values.keycloak.volumes.realmsPath }}
      volumes:
        - name: keycloak-realms
          emptyDir: {} # Replace with persistent volume configuration if needed
