apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-db-pvc
  labels:
    app: keycloak-db
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.config.storageClassName }}
  storageClassName: {{ .Values.config.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.keycloak.db.storageSize | default "10Gi" }}
