apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-keycloak
  labels:
    app: keycloak
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 30081
      targetPort: 30081
      nodePort: 30081 # NodePort range: 30000-32767
  selector:
    app: keycloak
    release: {{ .Release.Name }}

