{{- $secretName := printf "%s-keycloak-secrets" .Release.Name }}
{{- $existing := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- if not $existing }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: Opaque
data:
  admin-password: {{ (.Values.keycloak.adminPassword | default (randAlphaNum 24)) | b64enc }}
  client-secret: {{ (.Values.keycloak.clientSecret | default (randAlphaNum 32)) | b64enc }}
  db-password: {{ (.Values.keycloak.db.password | default (randAlphaNum 32)) | b64enc }}
{{- end }}
