apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-keycloak
  labels:
    app: keycloak
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.keycloak.replicas }}
  selector:
    matchLabels:
      app: keycloak
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: keycloak
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: keycloak
          image: "{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}"
          imagePullPolicy: "{{ .Values.keycloak.image.pullPolicy }}"
          ports:
            - containerPort: 8081
          {{- if not (eq .Values.environment "gke") }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthCheck.keycloak.readinessPath }}
              port: {{ .Values.healthCheck.keycloak.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: {{ .Values.healthCheck.keycloak.livenessPath }}
              port: {{ .Values.healthCheck.keycloak.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- end }}
          env:
            - name: KC_HTTP_PORT
              value: "8081"
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.keycloak.adminUser }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: {{ .Values.keycloak.adminPassword }}
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL_HOST
              value: keycloak-db
            - name: KC_DB_DATABASE
              value: {{ .Values.keycloak.db.database }}
            - name: KC_DB_USERNAME
              value: {{ .Values.keycloak.db.user }}
            - name: KC_DB_PASSWORD
              value: {{ .Values.keycloak.db.password }}
            - name: KC_HOSTNAME
              value: {{ .Values.keycloakHostname }}
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KEYCLOAK_LOGLEVEL
              value: DEBUG
            - name: ROOT_LOGLEVEL
              value: DEBUG
            - name: ROOT_URL
              value: https://{{ .Values.subdomain }}/
            - name: REDIRECT_URIS
              value: {{ .Values.sentriusDomain }}
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: GOOGLE_CLIENT_ID
              value: {{ .Values.keycloak.clientId }}
            - name: GOOGLE_CLIENT_SECRET
              value: {{ .Values.keycloak.clientSecret }}
          command: [ "/opt/keycloak/bin/kc.sh" ]
          args: [ "start-dev", "--proxy=edge", "--import-realm", "--health-enabled=true"]
