apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-keycloak-secrets" .Release.Name }}
type: Opaque
data:
  admin-password: {{ .Values.keycloak.adminPassword | b64enc }}
  client-secret: {{ .Values.keycloak.clientSecret | b64enc }}
  db-password: {{ .Values.keycloak.db.password | b64enc }}
