apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-db
  labels:
    app: keycloak-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      containers:
        - name: keycloak-db
          image: {{ .Values.keycloak.db.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.keycloak.db.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.keycloak.db.password }}
            - name: POSTGRES_DB
              value: {{ .Values.keycloak.db.database }}
          volumeMounts:
            - name: keycloak-db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: keycloak-db-data
          emptyDir: {} # Replace with persistent volume configuration if needed
