{{- if and (ne .Values.environment "local") (.Values.certificates.enabled) }}
---
{{- if eq .Values.environment "gke" }}
# GKE Managed Certificate
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: wildcard-cert-{{ .Values.tenant }}
spec:
  domains:
    - "{{ .Values.subdomain }}"
    - "{{ .Values.keycloakSubdomain }}"
    - "{{ .Values.agentproxySubdomain }}"
{{- else if or (eq .Values.environment "aws") (eq .Values.environment "azure") }}
# Cert-Manager Certificate for AWS or Azure
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert-{{ .Values.tenant }}
spec:
  secretName: wildcard-cert-{{ .Values.tenant }}
  issuerRef:
    name: {{ .Values.certificates.issuer }}
    kind: ClusterIssuer
  dnsNames:
    - "{{ .Values.subdomain }}"
    - "{{ .Values.keycloakSubdomain }}"
    - "{{ .Values.agentproxySubdomain }}"
{{- end }}
{{- else if and (eq .Values.environment "local") (.Values.certificates.enabled) }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: dev-ca-issuer
spec:
  ca:
    secretName: sentrius-dev-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert-{{ .Values.tenant }}
  namespace: {{ .Values.tenant }}
spec:
  secretName: wildcard-cert-{{ .Values.tenant }}
  issuerRef:
    name: dev-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - "{{ .Values.subdomain }}"
    - "{{ .Values.keycloakSubdomain }}"
    - "{{ .Values.agentproxySubdomain }}"
  subject:
    organizations:
      - sentrius-local
{{- end }}
