apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-monitoring-agent
  labels:
    {{- include "monitoring-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: monitoring-agent
  template:
    metadata:
      labels:
        app: monitoring-agent
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: [ 'sh', '-c', 'until nc -z {{ .Release.Name }}-postgres 5432; do echo waiting for postgres; sleep 2; done;' ]
      containers:
        - name: sentrius-agent
          image: "{{ .Values.monitoringagent.image.repository }}:{{ .Values.monitoringagent.image.tag }}"
          imagePullPolicy: {{ .Values.monitoringagent.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.monitoringagent.port }}
          volumeMounts:
            - name: config-volume
              mountPath: /config
          env:
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-oauth2-secrets
                  key: monitoring-agent-client-secret
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-config
