{{- if .Values.neo4j.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-neo4j-secrets
type: Opaque
data:
  # Neo4j Authentication String (username/password)
  {{- if .Values.neo4j.env.NEO4J_AUTH }}
  neo4j-auth: {{ .Values.neo4j.env.NEO4J_AUTH | b64enc }}
  {{- else }}
  neo4j-auth: {{ printf "neo4j/%s" (randAlphaNum 16) | b64enc }}
  {{- end }}
{{- end }}