apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.config.storageClassName }}
  storageClassName: {{ .Values.config.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize | default "10Gi" }}
