apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-pvc
  labels:
    app: qdrant
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.config.storageClassName }}
  storageClassName: {{ .Values.config.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.qdrant.storageSize | default "10Gi" }}
