apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-pvc
  labels:
    app: qdrant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.qdrant.storageSize | default "10Gi" }}
