apiVersion: v1
kind: Service
metadata:
  name: sentrius-rdp-proxy
  annotations:
    {{- if eq .Values.environment "gke" }}
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: |
      {
        "ports": {
          "http": "rdpproxy-backend-config"
        }
      }
    {{- else if eq .Values.environment "aws" }}
    {{- range $key, $value := .Values.sentrius.annotations.aws }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
    {{- else if eq .Values.environment "azure" }}
    {{- range $key, $value := .Values.sentrius.annotations.azure }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
    {{- end }}
  labels:
    app: sentrius-rdp-proxy
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.rdpproxy.serviceType }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: sentrius-rdp-proxy