apiVersion: v1
kind: Service
metadata:
  name: sentrius-rdp-proxy
  labels:
    app: sentrius-rdp-proxy
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.rdpproxy.serviceType }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: sentrius-rdp-proxy