apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  db-username: {{ (.Values.secrets.db.username | default "admin") | b64enc }}
  db-password: {{ (.Values.secrets.db.password | default (randAlphaNum 32)) | b64enc }}
  keystore-password: {{ (.Values.secrets.db.keystorePassword | default (randAlphaNum 24)) | b64enc }}
