apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
data:
  {{- if .Values.secrets.db.username }}
  db-username: {{ .Values.secrets.db.username | b64enc }}
  {{- else }}
  db-username: {{ "admin" | b64enc }}
  {{- end }}
  {{- if .Values.secrets.db.password }}
  db-password: {{ .Values.secrets.db.password | b64enc }}
  {{- else }}
  db-password: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  {{- if .Values.secrets.db.keystorePassword }}
  keystore-password: {{ .Values.secrets.db.keystorePassword | b64enc }}
  {{- else }}
  keystore-password: {{ randAlphaNum 24 | b64enc }}
  {{- end }}
