apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
data:
  db-username: {{ .Values.secrets.db.username }}
  db-password: {{ .Values.secrets.db.password }}
  keystore-password: {{ .Values.secrets.db.keystorePassword }}
