apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sentrius
  namespace: {{ .Values.tenant }}
  annotations:
    {{- if eq .Values.environment "gke" }}
    cloud.google.com/backend-config: '{"default": "sentrius-backend-config"}'
    {{- else if eq .Values.environment "aws" }}
    {{- range $key, $value := .Values.sentrius.annotations.aws }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
    {{- else if eq .Values.environment "azure" }}
    {{- range $key, $value := .Values.sentrius.annotations.azure }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
    {{- end }}
  labels:
    app: sentrius
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.sentrius.port }}
      targetPort: {{ .Values.sentrius.port }} # Port used inside the container
  selector:
    app: sentrius