apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ssh-agent
  namespace: {{ .Values.tenant }}
spec:
  type: {{ .Values.sshagent.service.type }}
  ports:
    - name: http
      port: {{ .Values.sshagent.port }}
      targetPort: {{ .Values.sshagent.port }} # Port used inside the container
      {{- if eq .Values.sshagent.service.type "NodePort" }}
      nodePort: {{ .Values.sshagent.nodePort | default 30088 }}
      {{- end }}
  selector:
    app: ssh-agent