apiVersion: v1
kind: Service
metadata:
  name: sentrius-ssh-proxy
  labels:
    app: sentrius-ssh-proxy
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.sshproxy.serviceType }}
  ports:
    - port: {{ .Values.sshproxy.port }}
      targetPort: {{ .Values.sshproxy.port }}
      protocol: TCP
      name: ssh
      {{- if and (eq .Values.sshproxy.serviceType "NodePort") .Values.sshproxy.nodePort }}
      nodePort: {{ .Values.sshproxy.nodePort }}
      {{- end }}
    - port: 8090
      targetPort: 8090
      protocol: TCP
      name: http
  selector:
    app: sentrius-ssh-proxy