{{- if .Values.surrealdb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-surrealdb
  labels:
    app: surrealdb
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.surrealdb.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: surrealdb
    release: {{ .Release.Name }}
{{- end }}
