{{- if .Values.surrealdb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-surrealdb-secret
  labels:
    app: surrealdb
    release: {{ .Release.Name }}
type: Opaque
data:
  # SurrealDB root password
  password: {{ .Values.surrealdb.password | default (randAlphaNum 24) | b64enc | quote }}
{{- end }}
