apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Values.tenant }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - host: keycloak.{{ .Values.tenant }}.sentrius.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8081
    - host: {{ .Values.tenant }}.sentrius.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sentrius
                port:
                  number: 8080
