apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-keycloak
  namespace: {{ .Values.tenant }}
  annotations:
      {{- if eq .Values.environment "gke" }}
      {{- range $key, $value := .Values.keycloak.annotations.gke }}
      {{ $key }}: "{{ $value }}"
      {{- end }}
      {{- else if eq .Values.environment "aws" }}
      {{- range $key, $value := .Values.keycloak.annotations.aws }}
      {{ $key }}: "{{ $value }}"
      {{- end }}
      {{- else if eq .Values.environment "azure" }}
      {{- range $key, $value := .Values.keycloak.annotations.azure }}
      {{ $key }}: "{{ $value }}"
      {{- end }}
      {{- end }}
  labels:
    app: keycloak
    release: {{ .Release.Name }}

spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.keycloak.port }}
      targetPort: {{ .Values.keycloak.port }} # Replace with the internal port Keycloak listens to
  selector:
    app: keycloak
    release: {{ .Release.Name }}