apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: keycloak-backend-config
  namespace: {{ .Values.tenant }}
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
    requestPath: /health/ready
    port: 8081
