apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-db
  labels:
    app: keycloak-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      containers:
        - name: keycloak-db
          image: {{ .Values.keycloak.db.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.keycloak.db.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.keycloak.db.password }}
            - name: POSTGRES_DB
              value: {{ .Values.keycloak.db.database }}
            - name: PGDATA
              value: /mnt/keycloak-db/data
          volumeMounts:
            - name: keycloak-db-data
              mountPath: /mnt/keycloak-db
      volumes:
        - name: keycloak-db-data
          persistentVolumeClaim:
            claimName: keycloak-db-pvc