apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sentrius
  namespace: {{ .Values.tenant }}
  annotations:
    cloud.google.com/backend-config: '{"default": "sentrius-backend-config"}'
  labels:
    app: sentrius
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.sentrius.port }}
      targetPort: {{ .Values.sentrius.port }} # Port used inside the container
  selector:
    app: sentrius