apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sentrius
  labels:
    app: sentrius
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.sentrius.port }} # Port used inside the container
  selector:
    app: sentrius