{{- include "keycloak.requireDbPassword" . }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keycloak-secrets
type: Opaque
data:
  # Keycloak Admin Password
  {{- if .Values.keycloak.adminPassword }}
  admin-password: {{ .Values.keycloak.adminPassword | b64enc }}
  {{- else }}
  admin-password: {{ randAlphaNum 24 | b64enc }}
  {{- end }}
  
  # Keycloak Client Secret
  {{- if .Values.keycloak.clientSecret }}
  client-secret: {{ .Values.keycloak.clientSecret | b64enc }}
  {{- else }}
  client-secret: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  # Keycloak Database Password
  db-password: {{ .Values.keycloak.db.password | b64enc }}