package io.sentrius.sso.core.model.automation;

import io.sentrius.sso.core.model.users.User;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.sql.Timestamp;

/**
 * Entity representing an automation suggestion generated by analyzing session patterns.
 * The analyzer reviews terminal logs and RDP sessions to identify repetitive tasks
 * that can be automated.
 */
@Entity
@Table(name = "automation_suggestions")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AutomationSuggestion {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    /**
     * Comma-separated list of session IDs that were analyzed to generate this suggestion
     */
    @Column(name = "session_ids", columnDefinition = "TEXT")
    private String sessionIds;
    
    /**
     * The suggested automation script (Python or Bash)
     */
    @Column(name = "suggested_script", nullable = false, columnDefinition = "TEXT")
    private String suggestedScript;
    
    /**
     * Human-readable description of what the automation does
     */
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;
    
    /**
     * Type of script: "python" or "bash"
     */
    @Column(name = "script_type", nullable = false)
    private String scriptType;
    
    /**
     * Status: PENDING, APPROVED, REJECTED, CONVERTED
     */
    @Column(name = "status", nullable = false)
    private String status;
    
    /**
     * Confidence score from the analyzer (0.0 to 1.0)
     */
    @Column(name = "confidence_score")
    private Double confidenceScore;
    
    /**
     * Number of sessions that exhibited this pattern
     */
    @Column(name = "pattern_frequency")
    private Integer patternFrequency;
    
    /**
     * User who would benefit from this automation (nullable - can be suggested for multiple users)
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "suggested_for_user_id")
    private User suggestedForUser;
    
    /**
     * Target system identifier where automation should run
     */
    @Column(name = "target_system")
    private String targetSystem;
    
    /**
     * When this suggestion was created
     */
    @Column(name = "created_at", columnDefinition = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
    private Timestamp createdAt;
    
    /**
     * When this suggestion was last updated
     */
    @Column(name = "updated_at")
    private Timestamp updatedAt;
    
    /**
     * Reference to the Automation entity if this suggestion was approved and converted
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "automation_id")
    private Automation automation;
    
    /**
     * Additional metadata in JSON format
     */
    @Column(name = "metadata", columnDefinition = "TEXT")
    private String metadata;
    
    @PrePersist
    protected void onCreate() {
        createdAt = new Timestamp(System.currentTimeMillis());
        updatedAt = createdAt;
        if (status == null) {
            status = "PENDING";
        }
    }
    
    @PreUpdate
    protected void onUpdate() {
        updatedAt = new Timestamp(System.currentTimeMillis());
    }
}
